"""add horoscope related tables

Revision ID: 03b05c8608da
Revises: 53d7b8dc9fd3
Create Date: 2025-10-25 22:39:08.735711

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "03b05c8608da"
down_revision = "53d7b8dc9fd3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_id", table_name="user")
    op.drop_index("ix_user_username", table_name="user")
    op.drop_table("user")
    op.drop_index("ix_horoscope_date", table_name="horoscope")
    op.drop_index("ix_horoscope_id", table_name="horoscope")
    op.drop_index("ix_horoscope_sign", table_name="horoscope")
    op.drop_table("horoscope")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "horoscope",
        sa.Column("sign", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("author", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="horoscope_pkey"),
    )
    op.create_index("ix_horoscope_sign", "horoscope", ["sign"], unique=False)
    op.create_index("ix_horoscope_id", "horoscope", ["id"], unique=False)
    op.create_index("ix_horoscope_date", "horoscope", ["date"], unique=False)
    op.create_table(
        "user",
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
    )
    op.create_index("ix_user_username", "user", ["username"], unique=True)
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    # ### end Alembic commands ###
