"""add role managment table

Revision ID: e2c0ae0e4529
Revises:
Create Date: 2025-10-24 15:53:51.427882

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2c0ae0e4529"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "horoscope",
        sa.Column("sign", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_horoscope_date"), "horoscope", ["date"], unique=False)
    op.create_index(op.f("ix_horoscope_id"), "horoscope", ["id"], unique=False)
    op.create_index(op.f("ix_horoscope_sign"), "horoscope", ["sign"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_horoscope_sign"), table_name="horoscope")
    op.drop_index(op.f("ix_horoscope_id"), table_name="horoscope")
    op.drop_index(op.f("ix_horoscope_date"), table_name="horoscope")
    op.drop_table("horoscope")
    # ### end Alembic commands ###
