"""rename table

Revision ID: f48d73abd82f
Revises: 03b05c8608da
Create Date: 2025-10-25 22:43:25.699817

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f48d73abd82f"
down_revision = "03b05c8608da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
